---
title: "Parcels"
author: "Andronikos Gyrichidis"
date: "1 September 2016"
output: html_document
---

```{r, include = FALSE}
library(raster)
library(leaflet)
library(rgdal)
library(rgeos)

idParcel <- 17

sfile <- readOGR("E:/GisParcels/newTest.shp", "newTest")
newTest <- sfile[sfile@data$Id == idParcel, ]
nameParcel <- as.matrix(as.data.frame(newTest))
nameParcel <- nameParcel[1, 2]
mag <- nameParcel

col <- c("#a50026", "#d73027", "#f46d43", "#fdae61", "#fee08b", "#d9ef8b", "#a6d96a", "#66bd63", "#1a9850", "#006837")

```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(raster)
library(leaflet)
library(rgdal)
library(rgeos)

ndvi_0610 <- raster('E:/SubSetsStudyAreas/R051_V20160610T105555/studyarea_ndvi_20160610.img')
ndvi_0710 <- raster('E:/SubSetsStudyAreas/R051_V20160710T105247/studyarea_ndvi_20160710.img')
ndvi_0720 <- raster('E:/SubSetsStudyAreas/R051_V20160720T105547/studyarea_ndvi_20160720.img')

interMapNdvi1 <- ndvi_0610
interMapNdvi2 <- ndvi_0710
interMapNdvi3 <- ndvi_0720

interMapNdvi1 <- crop(interMapNdvi1, extent(newTest))
interMapNdvi2 <- crop(interMapNdvi2, extent(newTest))
interMapNdvi3 <- crop(interMapNdvi3, extent(newTest))

palndvi1 <- colorNumeric(col, values(interMapNdvi1), na.color = "transparent")
palndvi2 <- colorNumeric(col, values(interMapNdvi2), na.color = "transparent")
palndvi3 <- colorNumeric(col, values(interMapNdvi3), na.color = "transparent")

library(leaflet)
leaflet() %>% 
  addMarkers(5.013236, 50.641028, popup = mag, options=popupOptions(closeButton=FALSE)) %>%
  #addTiles(group = "Open Street Map") %>%
  addProviderTiles("Esri.WorldImagery", group = "Esri Map") %>%
  
  addRasterImage(x = interMapNdvi1, colors = palndvi1, opacity = 1, group = "June10") %>%
  addRasterImage(x = interMapNdvi2, colors = palndvi2, opacity = 1, group = "July10") %>%
  addRasterImage(x = interMapNdvi3, colors = palndvi3, opacity = 1, group = "July20") %>%
  
  addLegend("topright", pal = palndvi2, values = values(interMapNdvi2),title = "ndvi") %>%
  addLayersControl(baseGroups = c("Esri Map"), overlayGroups = c("June10", "July10", "July20")) %>%
hideGroup(c("July10", "July20"))

```

Hoe


```{r, echo = FALSE, message = FALSE, warning = FALSE}
gndvi_0610 <- raster('E:/SubSetsStudyAreas/R051_V20160610T105555/studyarea_gndvi_20160610.img')
gndvi_0710 <- raster('E:/SubSetsStudyAreas/R051_V20160710T105247/studyarea_gndvi_20160710.img')
gndvi_0720 <- raster('E:/SubSetsStudyAreas/R051_V20160720T105547/studyarea_gndvi_20160720.img')

interMapGndvi1 <- gndvi_0610
interMapGndvi2 <- gndvi_0710
interMapGndvi3 <- gndvi_0720

interMapGndvi1 <- crop(interMapGndvi1, extent(newTest))
interMapGndvi2 <- crop(interMapGndvi2, extent(newTest))
interMapGndvi3 <- crop(interMapGndvi3, extent(newTest))

palgndvi1 <- colorNumeric(col, values(interMapGndvi1), na.color = "transparent")
palgndvi2 <- colorNumeric(col, values(interMapGndvi2), na.color = "transparent")
palgndvi3 <- colorNumeric(col, values(interMapGndvi3), na.color = "transparent")

leaflet() %>% 
  addMarkers(5.013236, 50.641028, popup = mag, options=popupOptions(closeButton=FALSE)) %>%
  #addTiles(group = "Open Street Map") %>%
  addProviderTiles("Esri.WorldImagery", group = "Esri Map") %>%
  
  addRasterImage(x = interMapGndvi1, colors = palgndvi1, opacity = 1, group = "June10") %>%
  addRasterImage(x = interMapGndvi2, colors = palgndvi2, opacity = 1, group = "July10") %>%
  addRasterImage(x = interMapGndvi3, colors = palgndvi3, opacity = 1, group = "July20") %>%
  
  addLegend(pal = palgndvi3, values = values(interMapGndvi3),title = "gndvi") %>%
  addLayersControl(baseGroups = c("Esri Map"), overlayGroups = c("June10", "July10", "July20")) %>%
  hideGroup(c("July10", "July20"))
```


gaat


```{r, echo = FALSE, message = FALSE, warning = FALSE}
savi_0610 <- raster('E:/SubSetsStudyAreas/R051_V20160610T105555/studyarea_savi_20160610.img')
savi_0710 <- raster('E:/SubSetsStudyAreas/R051_V20160710T105247/studyarea_savi_20160710.img')
savi_0720 <- raster('E:/SubSetsStudyAreas/R051_V20160720T105547/studyarea_savi_20160720.img')

interMapSavi1 <- savi_0610
interMapSavi2 <- savi_0710
interMapSavi3 <- savi_0720

interMapSavi1 <- crop(interMapSavi1, extent(newTest))
interMapSavi2 <- crop(interMapSavi2, extent(newTest))
interMapSavi3 <- crop(interMapSavi3, extent(newTest))

palsavi1 <- colorNumeric(col, values(interMapSavi1), na.color = "transparent")
palsavi2 <- colorNumeric(col, values(interMapSavi2), na.color = "transparent")
palsavi3 <- colorNumeric(col, values(interMapSavi3), na.color = "transparent")

leaflet() %>% 
  addMarkers(5.013236, 50.641028, popup = mag, options=popupOptions(closeButton=FALSE)) %>%
  #addTiles(group = "Open Street Map") %>%
  #addPopups(642745.862, 5611975.724, mag) %>%
  addProviderTiles("Esri.WorldImagery", group = "Esri Map") %>%
  
  addRasterImage(x = interMapSavi1, colors = palsavi1, opacity = 1, group = "June10") %>%
  addRasterImage(x = interMapSavi2, colors = palsavi2, opacity = 1, group = "July10") %>%
  addRasterImage(x = interMapSavi3, colors = palsavi3, opacity = 1, group = "July20") %>%
  
  addLegend(pal = palsavi3, values = values(interMapSavi3),title = "savi") %>%
  addLayersControl(baseGroups = c("Esri Map"), overlayGroups = c("June10", "July10", "July20")) %>%
  hideGroup(c("July10", "July20"))
```

het


```{r, echo = FALSE, message = FALSE, warning = FALSE}
rvi_0610 <- raster('E:/SubSetsStudyAreas/R051_V20160610T105555/studyarea_rvi_20160610.img')
rvi_0710 <- raster('E:/SubSetsStudyAreas/R051_V20160710T105247/studyarea_rvi_20160710.img')
rvi_0720 <- raster('E:/SubSetsStudyAreas/R051_V20160720T105547/studyarea_rvi_20160720.img')

interMaprvi1 <- rvi_0610
interMaprvi2 <- rvi_0710
interMaprvi3 <- rvi_0720

interMaprvi1 <- crop(interMaprvi1, extent(newTest))
interMaprvi2 <- crop(interMaprvi2, extent(newTest))
interMaprvi3 <- crop(interMaprvi3, extent(newTest))

palrvi1 <- colorNumeric(col, values(interMaprvi1), na.color = "transparent")
palrvi2 <- colorNumeric(col, values(interMaprvi2), na.color = "transparent")
palrvi3 <- colorNumeric(col, values(interMaprvi3), na.color = "transparent")

leaflet() %>% 
  addMarkers(5.013236, 50.641028, popup = mag, options=popupOptions(closeButton=FALSE)) %>%
  #addTiles(group = "Open Street Map") %>%
  #addPopups(642745.862, 5611975.724, mag) %>%
  addProviderTiles("Esri.WorldImagery", group = "Esri Map") %>%
  
  addRasterImage(x = interMaprvi1, colors = palrvi1, opacity = 1, group = "June10") %>%
  addRasterImage(x = interMaprvi2, colors = palrvi2, opacity = 1, group = "July10") %>%
  addRasterImage(x = interMaprvi3, colors = palrvi3, opacity = 1, group = "July20") %>%
  
  addLegend(pal = palrvi1, values = values(interMaprvi1),title = "rvi") %>%
  addLayersControl(baseGroups = c("Esri Map"), overlayGroups = c("June10", "July10", "July20")) %>%
  hideGroup(c("July10", "July20"))
```

?
